apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pfa-deployment
  namespace: pfa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pfa
    spec:
      containers:
      - name: pfa
        image: puppet/pipelines-for-applications:latest
        ports:
        - containerPort: 7000
          hostPort: 7000
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - containerPort: 8000
          hostPort: 8000
          protocol: TCP
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              key: USER
              name: pfa-frontend-config
        - name: MYSQL_PWD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PWD
              name: pfa-frontend-config
        - name: DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: DB_ENDPOINT
              name: pfa-frontend-config
